# Generated by Django 5.2 on 2025-05-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('posted', models.DateField()),
                ('description', models.TextField()),
                ('requirements', models.JSONField()),
            ],
        ),
    ]
